# Frontend Nuxt 3.11.2
FROM node:20.18.3-alpine

WORKDIR /app

# Instalar dependencias necesarias para algunas librerías
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install -D tailwindcss@3.3.6 postcss@8 autoprefixer@10

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
