CREATE TABLE CLANS (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    categoria_id INT REFERENCES CATEGORIES(id) ON DELETE SET NULL,
    es_public BOOLEAN DEFAULT TRUE,
    max_membres INT NOT NULL CHECK (max_membres IN (10, 15, 20)),
    lider_id INT NOT NULL REFERENCES USUARIS(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLAN_MEMBERS (
    clan_id INT NOT NULL REFERENCES CLANS(id) ON DELETE CASCADE,
    usuari_id INT NOT NULL REFERENCES USUARIS(id) ON DELETE CASCADE,
    rol VARCHAR(20) DEFAULT 'miembro' CHECK (rol IN ('lider', 'miembro')),
    data_unio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (clan_id, usuari_id)
);

CREATE TABLE CLAN_REQUESTS (
    id SERIAL PRIMARY KEY,
    clan_id INT NOT NULL REFERENCES CLANS(id) ON DELETE CASCADE,
    usuari_id INT NOT NULL REFERENCES USUARIS(id) ON DELETE CASCADE,
    tipus VARCHAR(20) NOT NULL CHECK (tipus IN ('solicitud', 'invitacion')),
    estat VARCHAR(20) DEFAULT 'pendent' CHECK (estat IN ('pendent', 'acceptat', 'rebutjat')),
    invitador_id INT REFERENCES USUARIS(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLAN_MESSAGES (
    id SERIAL PRIMARY KEY,
    clan_id INT NOT NULL REFERENCES CLANS(id) ON DELETE CASCADE,
    usuari_id INT NOT NULL REFERENCES USUARIS(id) ON DELETE CASCADE,
    contingut TEXT NOT NULL,
    habit_id INT REFERENCES HABITS(id) ON DELETE SET NULL,
    plantilla_id INT REFERENCES PLANTILLES(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_clans_lider ON CLANS(lider_id);
CREATE INDEX idx_clans_public ON CLANS(es_public);
