name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar al servidor
    runs-on: ubuntu-latest

    steps:
    - name: Executar comandes SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/loopy
          git pull origin main

          # Crear l'arxiu .env de l'arrel a partir de secrets
          echo "${{ secrets.ENV_ARREL }}" > .env

          # Crear l'arxiu .env dins de backend-laravel a partir de secrets
          echo "${{ secrets.ENV_BACKEND }}" > backend-laravel/.env

          # Reconstruir imatges i aixecar contenidors
          docker-compose -f docker/docker-compose.yml build
          docker-compose -f docker/docker-compose.yml up -d

          # Esperar uns segons perquè la BD i els contenidors estiguin completament llestos abans de migrar
          sleep 10

          # Executar migracions de Laravel al contenidor adient i caché
          docker exec loopy-laravel php artisan migrate --force
          docker exec loopy-laravel php artisan config:cache
          docker exec loopy-laravel php artisan route:cache

          # Neteja d'imatges òrfenes per no omplir el disc del servidor
          docker image prune -f
